# -*- coding: utf-8 -*-
"""ProyectoMLsm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wCSsATK_sx0gevCFfbNtTnOphpCVm055
"""

#instalacion de streamlit
!pip install -q streamlit pyngrok pymongo pandas

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from pymongo import MongoClient
# from datetime import datetime
# @st.cache_resource
# def init_connection():
#    return MongoClient(st.secrets["MONGO_URI"])
# try:
#     client = init_connection()
#     db = client["mercadolibre"]
# except Exception as e:
#     st.error(f"Error de conexión: {e}")
# st.set_page_config(page_title="Mercado Libre", layout="wide", page_icon="")
# 
# 
# st.markdown("""
#     <style>
#     .stApp {
#         background-color: #111111;
#         color: #FFFFFF;
#     }
#     .sidebar .sidebar-content {
#         background-color: #1A1A1A;
#     }
#     h1, h2, h3 {
#         color: #E0E0E0 !important;
#         font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
#     }
#     .stMetric {
#         background-color: #222222;
#         padding: 15px;
#         border-radius: 10px;
#         border-left: 5px solid #E0E0E0;
#         box-shadow: 2px 2px 10px rgba(0,0,0,0.5);
#     }
#     .stMetric label {
#         color: #AAAAAA !important;
#     }
#     .stMetric div {
#         color: #E0E0E0 !important;
#     }
#     div[data-baseweb="tab-list"] button {
#         color: #FFFFFF !important;
#     }
#     div[data-baseweb="tab-list"] button[aria-selected="true"] {
#         color: #E0E0E0 !important;
#         border-bottom-color: #E0E0E0 !important;
#     }
#     .stButton>button {
#         background-color: #E0E0E0 !important;
#         color: #111111 !important;
#         font-weight: bold !important;
#         border: none !important;
#     }
#     .stButton>button:hover {
#         background-color: #CC1100 !important;
#         color: #FFFFFF !important;
#     }
#     </style>
#     """, unsafe_allow_html=True)
# st.sidebar.markdown("<h2 style='text-align: center; color: #E0E0E0;'>Navegación</h2>", unsafe_allow_html=True)
# 
# 
# modulo = st.sidebar.selectbox("Selecciona la sección", ["🏠 Inicio", "📦 Productos", "🛒 Pedidos", "👥 Usuarios"])
# if modulo == "🏠 Inicio":
#     st.markdown("<h1 style='text-align: center; font-size: 45px;'>🛍️ MERCADO LIBRE</h1>", unsafe_allow_html=True)
#     st.markdown("<p style='text-align: center; color: #AAAAAA; font-size: 18px;'>Panel Experto de Control, Analíticas e Inventario</p>", unsafe_allow_html=True)
#     st.image(
#     "https://http2.mlstatic.com/frontend-assets/ml-web-navigation/ui-navigation/6.6.131/mercadolibre/logo__large_plus.png",
#     width=300
# )
#     st.markdown("---")
#     prod_list = list(db["productos"].find())
#     ped_list = list(db["pedidos"].find())
#     usr_list = list(db["usuarios"].find())
#     ventas_totales = sum(float(p.get("total", 0)) for p in ped_list)
#     usuarios_activos = sum(1 for u in usr_list if u.get("estado") == "Activo")
#     productos_totales = len(prod_list)
#     ticket_promedio = ventas_totales / len(ped_list) if len(ped_list) > 0 else 0
#     st.markdown("### 📊 Indicadores Clave de Rendimiento (KPIs)")
#     col1, col2, col3, col4 = st.columns(4)
#     with col1:
#         st.metric(label="💰 Ventas Totales", value=f"${ventas_totales:,.2f}")
#     with col2:
#         st.metric(label="👥 Usuarios Activos", value=f"{usuarios_activos} activos")
#     with col3:
#         st.metric(label="📦 Catálogo de Productos", value=f"{productos_totales} ítems")
#     with col4:
#         st.metric(label="📈 Ticket Promedio", value=f"${ticket_promedio:,.2f}")
#     st.markdown("---")
# 
#     st.markdown("## 🛍️ Categorías Destacadas")
# 
#     cat1, cat2, cat3 = st.columns(3)
# 
#     with cat1:
#         st.image(
#             "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500",
#             caption="📱 Electrónica",
#             use_container_width=True
#         )
# 
#     with cat2:
#         st.image(
#             "https://images.unsplash.com/photo-1445205170230-053b83016050?w=500",
#             caption="👕 Moda",
#             use_container_width=True
#         )
# 
#     with cat3:
#         st.image(
#             "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500",
#             caption="🏠 Hogar",
#             use_container_width=True
#         )
# 
#     st.markdown("---")
#     col_izq, col_der = st.columns(2)
#     with col_izq:
#             st.markdown("### 🎯 Accesos Rápidos del Sistema")
#             st.info("💡 Consejo: Utiliza el menú del panel lateral izquierdo para navegar rápidamente entre los inventarios, altas de usuarios y auditoría de transacciones.")
#             st.warning("⚠️ Asegúrate de revisar periódicamente la lista de entregas pendientes en la pestaña de 'Pedidos' para garantizar la satisfacción del cliente.")
#     with col_der:
#             st.markdown("### 🛠️ Información del Entorno")
#             st.code(f"""Base de Datos: MongoDB Localhost\nEstado del Servidor: En línea (Conectado)\nColecciones Activas: 3 (productos, pedidos, usuarios)\nÚltima sincronización: {datetime.now().strftime('%H:%M:%S')}""", language="yaml")
# 
# elif modulo == "📦 Productos":
#     collection = db["productos"]
#     documentos = list(collection.find())
#     st.markdown("## 📦 Gestión de Inventario de Productos")
#     tab_leer, tab_crear, tab_actualizar, tab_eliminar = st.tabs(["📋 Ver Todos", "➕ Crear", "✏️ Actualizar", "❌ Eliminar"])
#     with tab_leer:
#         st.header("Lista de Productos Registrados")
# 
#         if documentos:
# 
#             st.caption(f"Total de productos en base de datos: {len(documentos)}")
# 
#             for doc in documentos:
# 
#                 categoria = str(doc.get("categoria", "")).lower()
# 
#                 if "elect" in categoria:
#                     imagen = "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500"
# 
#                 elif "moda" in categoria or "ropa" in categoria:
#                     imagen = "https://images.unsplash.com/photo-1445205170230-053b83016050?w=500"
# 
#                 elif "hogar" in categoria:
#                     imagen = "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500"
# 
#                 else:
#                     imagen = "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500"
# 
#                 col1, col2 = st.columns([1, 3])
# 
#                 with col1:
#                     st.image(imagen, width=150)
# 
#                 with col2:
#                     st.subheader(doc.get("nombre", "Sin nombre"))
#                     st.write(f"💲 Precio: ${doc.get('precio', 0)}")
#                     st.write(f"📦 Stock: {doc.get('stock', 0)}")
#                     st.write(f"🏷️ Marca: {doc.get('marca', '')}")
#                     st.write(f"📂 Categoría: {doc.get('categoria', '')}")
#                     st.write(f"📝 {doc.get('descripcion', '')}")
#                     st.write(f"🔵 Estado: {doc.get('estado', '')}")
# 
#                 st.markdown("---")
# 
#         else:
#             st.info("No hay productos registrados en la colección.")
# 
#     with tab_crear:
#         st.header("Registrar Nuevo Producto")
#         with st.form("form_crear_prod"):
#             c1, c2 = st.columns(2)
#             with c1:
#                 nuevo_id = st.number_input("ID numérico", min_value=1, step=1, value=1)
#                 nuevo_nombre = st.text_input("Nombre del Producto", placeholder="Ej. Smartphone")
#                 nuevo_precio = st.number_input("Precio ($)", min_value=0.0, step=0.5, value=100.0)
#                 nueva_categoria = st.text_input("Categoría", value="Electrónica")
#             with c2:
#                 nuevo_stock = st.number_input("Stock Inicial", min_value=0, step=1, value=10)
#                 nueva_marca = st.text_input("Marca", value="Genérica")
#                 nueva_descripcion = st.text_area("Descripción", placeholder="Breve descripción...")
#                 nuevo_estado = st.selectbox("Estado del Producto", ["Activo", "Inactivo"])
#             boton_guardar = st.form_submit_button("Guardar Producto")
#             if boton_guardar:
#                 if nuevo_nombre.strip() == "":
#                     st.error("El nombre no puede estar vacío.")
#                 else:
#                     nuevo_documento = {
#                         "id": int(nuevo_id),
#                         "nombre": nuevo_nombre,
#                         "precio": nuevo_precio,
#                         "categoria": nueva_categoria,
#                         "stock": int(nuevo_stock),
#                         "marca": nueva_marca,
#                         "descripcion": nueva_descripcion,
#                         "estado": nuevo_estado
#                     }
#                     collection.insert_one(nuevo_documento)
#                     st.success(f"✅ ¡Producto '{nuevo_nombre}' agregado!")
#                     st.rerun()
#     with tab_actualizar:
#         st.header("Modificar un Producto Existente")
#         if documentos:
#             opciones_productos = {f"{doc.get('nombre', 'Sin Nombre')} (ID: {doc.get('id', 'N/A')})": doc for doc in documentos}
#             seleccion = st.selectbox("Selecciona el producto a editar:", opciones_productos.keys())
#             prod_actual = opciones_productos[seleccion]
#             with st.form("form_actualizar_prod"):
#                 c3, c4 = st.columns(2)
#                 with c3:
#                     edit_nombre = st.text_input("Nombre del Producto", value=prod_actual.get('nombre', ''))
#                     edit_precio = st.number_input("Precio ($)", min_value=0.0, step=0.5, value=float(prod_actual.get('precio', 0)))
#                     edit_categoria = st.text_input("Categoría", value=prod_actual.get('categoria', ''))
#                 with c4:
#                     edit_stock = st.number_input("Stock", min_value=0, step=1, value=int(prod_actual.get('stock', 0)))
#                     edit_marca = st.text_input("Marca", value=prod_actual.get('marca', ''))
#                     edit_descripcion = st.text_area("Descripción", value=prod_actual.get('descripcion', ''))
#                     edit_estado = st.selectbox("Estado del Producto", ["Activo", "Inactivo"], index=0 if prod_actual.get('estado') == "Activo" else 1)
#                 boton_actualizar = st.form_submit_button("Actualizar Cambios")
#                 if boton_actualizar:
#                     collection.update_one(
#                         {"_id": prod_actual["_id"]},
#                         {"$set": {
#                             "nombre": edit_nombre,
#                             "precio": edit_precio,
#                             "categoria": edit_categoria,
#                             "stock": int(edit_stock),
#                             "marca": edit_marca,
#                             "descripcion": edit_descripcion,
#                             "estado": edit_estado
#                         }}
#                     )
#                     st.success("✏️ ¡Producto actualizado!")
#                     st.rerun()
#         else:
#             st.info("No hay productos disponibles para editar.")
#     with tab_eliminar:
#         st.header("Eliminar Producto")
#         if documentos:
#             opciones_eliminar = {f"{doc.get('nombre')} (ID: {doc.get('id')})": doc for doc in documentos}
#             seleccion_del = st.selectbox("Selecciona el producto a eliminar:", opciones_eliminar.keys(), key="del_prod")
#             prod_a_borrar = opciones_eliminar[seleccion_del]
#             if st.button("🚨 Confirmar Eliminación Permanente", type="primary"):
#                 collection.delete_one({"_id": prod_a_borrar["_id"]})
#                 st.warning(f"Producto '{prod_a_borrar.get('nombre')}' eliminado.")
#                 st.rerun()
#         else:
#             st.info("No hay productos para eliminar.")
# elif modulo == "🛒 Pedidos":
#     collection_pedidos = db["pedidos"]
#     pedidos = list(collection_pedidos.find())
#     st.markdown("## 🛒 Historial y Registro de Pedidos")
#     tab_leer_p, tab_crear_p = st.tabs(["📋 Ver Pedidos", "➕ Registrar Pedido"])
#     with tab_leer_p:
#         st.header("Todos los Pedidos Registrados")
# 
#         if pedidos:
#             st.data_editor(
#                 pedidos,
#                 use_container_width=True,
#                 disabled=True
#             )
# 
#             st.caption(
#                 f"Total de pedidos registrados: {len(pedidos)}"
#             )
# 
#         else:
#             st.info("No hay pedidos registrados en la colección.")
#     with tab_crear_p:
#         st.header("Dar de Alta un Pedido")
#         with st.form("form_crear_pedido"):
#             c5, c6 = st.columns(2)
# 
#             with c5:
#                 id_pedido = st.number_input("ID del Pedido", min_value=1, step=1)
#                 id_usuario = st.number_input("ID Usuario", min_value=1, step=1)
#                 id_producto = st.number_input("ID Producto", min_value=1, step=1)
#                 fecha_pedido = st.date_input("Fecha del Pedido")
# 
#             with c6:
#                 cantidad = st.number_input("Cantidad", min_value=1, step=1)
#                 total = st.number_input("Total ($)", min_value=0.0, step=0.5)
#                 estado = st.selectbox(
#                     "Estado",
#                     ["Pendiente", "Enviado", "Entregado", "Cancelado"]
#                 )
#                 metodo_pago = st.selectbox(
#                     "Método de Pago",
#                     ["Tarjeta", "Transferencia", "Efectivo", "PayPal"]
#                 )
# 
#             boton_pedido = st.form_submit_button("Registrar Pedido")
# 
#             if boton_pedido:
#                 nuevo_pedido = {
#                     "id": int(id_pedido),
#                     "id_usuario": int(id_usuario),
#                     "id_producto": int(id_producto),
#                     "fecha_pedido": datetime.combine(
#                         fecha_pedido,
#                         datetime.min.time()
#                     ),
#                     "cantidad": int(cantidad),
#                     "total": float(total),
#                     "estado": estado,
#                     "metodo_pago": metodo_pago
#                 }
# 
#                 collection_pedidos.insert_one(nuevo_pedido)
#                 st.success("🛒 Pedido registrado correctamente")
#                 st.rerun()
# 
# elif modulo == "👥 Usuarios":
#     collection_usuarios = db["usuarios"]
#     usuarios = list(collection_usuarios.find())
#     st.markdown("## 👥 Base de Datos de Usuarios")
#     tab_leer_u, tab_crear_u = st.tabs(["📋 Lista de Usuarios", "➕ Registrar Usuario"])
#     with tab_leer_u:
#         st.header("Usuarios Registrados en el Sistema")
#         if usuarios:
#             st.data_editor(usuarios, use_container_width=True, disabled=True)
#             st.caption(f"Total de clientes/usuarios: {len(usuarios)}")
#         else:
#             st.info("No hay usuarios registrados en la colección.")
#     with tab_crear_u:
#         st.header("Registrar Cuenta de Usuario")
#         with st.form("form_crear_usuario"):
#             c7, c8 = st.columns(2)
#             with c7:
#                 id_u = st.number_input("ID de Usuario", min_value=1, step=1, value=1)
#                 nombre_u = st.text_input("Nombre")
#                 apellido_u = st.text_input("Apellido")
#                 correo_u = st.text_input("Correo Electrónico")
#             with c8:
#                 telefono_u = st.text_input("Teléfono")
#                 direccion_u = st.text_area("Dirección de Envío")
#                 fecha_reg = st.date_input("Fecha de Registro", value=datetime.now())
#                 estado_u = st.selectbox("Estado del Usuario", ["Activo", "Inactivo"])
#             boton_usuario = st.form_submit_button("Dar de Alta Usuario")
#             if boton_usuario:
#                 if nombre_u.strip() == "" or correo_u.strip() == "":
#                     st.error("Nombre y Correo son obligatorios.")
#                 else:
#                     nuevo_u = {
#                         "id": int(id_u),
#                         "nombre": nombre_u,
#                         "apellido": apellido_u,
#                         "correo": correo_u,
#                         "telefono": telefono_u,
#                         "direccion": direccion_u,
#                         "fecha_registro": datetime.combine(fecha_reg, datetime.min.time()),
#                         "estado": estado_u
#                     }
#                     collection_usuarios.insert_one(nuevo_u)
#                     st.success(f"👥 ¡Usuario '{nombre_u}' creado con éxito!")
#                     st.rerun()

#Ejecutar Streamlit
!nohup streamlit run app.py &
!npx localtunnel --port 8501 & curl ipv4.icanhazip.com
